### ISSUE TITLE
画像出力機能の実装

### ISSUE THREAD

**Issue by subaru-saito1** [Yuma-Saito/sudokizer#44]
canvasを画像形式でダウンロードする
カーソルは一旦非表示にするなど工夫が必要

**Comment by Yuma-Saito** [comment]
セキュリティ強化によって結構面倒なプロセスを踏まないと行けなそうだ。
保留。

**Comment by subaru-saito1** [comment]
実装した部分
- [x] 画像をダウンロードする
- [x] カーソルを非表示にする
- [x] サイズを別途指定する
