### ISSUE TITLE
候補数字に仮定レベルに応じた色がつかない

### ISSUE THREAD

**Issue by subaru-saito1** [Yuma-Saito/sudokizer#54]
原因究明と調査

**Comment by Yuma-Saito** [comment]
#55と一緒に修正する予定

**Comment by subaru-saito1** [comment]
#55 のカオスコミットでちょっとやりましたが、
候補数字ごとに仮定レベルの情報をもたないといけないのでした。

**Comment by subaru-saito1** [comment]
- [x] Cellクラスの中
- [x] 入力部分（二度手間になるけど脳内の整理のためいったん）
- [x] 表示部分

**Comment by subaru-saito1** [comment]
多分バグはあるけど見つかったらまたissue立てます
